### ISSUE TITLE
create a page & video demo of how to take any old spring boot maven project and fabric8 enable it

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-spring#1]
either using JBoss Forge (CLI / IDE) like at 13:00 of this video https://vimeo.com/180053437  or using the new [mvn fabric8:enable goal](https://github.com/fabric8io/fabric8-maven-plugin/issues/298)

**Comment by jstrachan** [comment]
the project could come from an existing project or via using start.spring.io etc

**Comment by jstrachan** [comment]
I guess we should explain that this step is not required for any of the fabric8 archeypes folks could create via mvn or their IDE

**Comment by rawlingsj** [comment]
yeah I was gonna add from an IDE too

**Comment by jstrachan** [comment]
I guess there's lots of options
- create from start.spring.io on website (or in forge CLI / IDE or fabric8 console)
- migrate existing project (forge setup / mvn fabric8 setup)
- from fabric8 archetype CLI / IDE / fabric8 console

Its only the first 2 requires the 'fabric8 setup' stuff

**Comment by jstrachan** [comment]
migrating an existing project should be given its own page and video though, as its gonna be super common - take any project from anywhere & fabric8 enable it etc

**Comment by jstrachan** [comment]
added a page now: https://github.com/fabric8io/fabric8-spring/blob/master/docs/getting-started.md#spring-initializr-or-existing-spring-projects
